USE bi_and_dw;
CREATE TABLE IF NOT EXISTS bi_and_dw.fact_table (
    trip_id INT AUTO_INCREMENT PRIMARY KEY,
    vendor_id BIGINT,
    date_id INT,
    location_id INT,
    rate_id INT,
    payment_id INT,
    passenger_count INT,
    trip_distance DOUBLE,
    trip_time_minutes INT,
    fare_amount DOUBLE,
    extra DOUBLE,
    mta_tax DOUBLE,
    improvement_surcharge DOUBLE,
    congestion_surcharge DOUBLE,
    airport_fee DOUBLE,
    tip_amount DOUBLE,
    tip_percentage DOUBLE,
    tolls_amount DOUBLE,
    total_amount DOUBLE,
    fare_per_minute DOUBLE,
    tip_per_minute DOUBLE,
    avg_mph DOUBLE,
    store_and_fwd_flag VARCHAR(1),
    FOREIGN KEY (vendor_id) REFERENCES vendor_dimension(vendor_id),
    FOREIGN KEY (date_id) REFERENCES datetime_dimension(date_id),
    FOREIGN KEY (location_id) REFERENCES location_dimension(location_id),
    FOREIGN KEY (rate_id) REFERENCES rate_dimension(rate_id),
    FOREIGN KEY (payment_id) REFERENCES paymenttype_dimension(payment_id)
);
